### ISSUE TITLE
Morning session code review with coding partners

### ISSUE THREAD

**Issue by aceDavon** [Rn486/Recillah-Khamala-Portfolio#5]
Great work done so far, the design is elegant and expressive with fonts properly formatted. Just a few additions and adjustments as observed and listed below:
- The form section is not aligned correctly and formated. You could try to resize the form so to fit the template design from Figma.
- Your linters check failed for this commit, so you could rerun the tests locally to confirm you fixed the errors before pushing again.

**Comment by DebbyMiressa** [comment]
An additional thing to improve on:
- Your background pictures look stretched. Please assign a width and height to the background images.

**Comment by Recillah-Khamala** [comment]
Thank you for the kind words and help in heading to the right direction, the changes have been actioned.
