### ISSUE TITLE
Bugs in the javascript code

### ISSUE THREAD

**Issue by TracyMuso** [Rn486/Recillah-Khamala-Portfolio#8]
Hi Recillah! Kudos for coming so far in your project, I found some bugs in your javascript file that might cause some trouble. I came up with the solution too! These are all from your popup-window branch in your pwindow.js file

**Suggested changes**
-In line 60, you wrote this `tag.classList.add(tech)` , I recommend you add single quotes to tech, like this `('tech')` in order to create the class, do this for the rest of the other classes you are trying to create.
-In lines 59 and 107, you used the URL interface incorrectly,  you wrote `URL.append(tag)`. The URL interface is used to parse, construct, normalize, and encode URLs. Please use it like this `URL('url')`.
-This is for best practice, please add semicolon at the end of all your functions, variables etc.
-Last but not least, I see you were trying to loop through your tdetail array with the for each method. I suggest you use this format `array.forEach((element, index, array)`...rather than `array.element.forEach(element, index, array)`

**All the best with your project!**

**Comment by Recillah-Khamala** [comment]
fixed
